### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by lifeart** [stefanpenner/broccoli-swc#3]
https://github.com/stefanpenner/broccoli-swc/blob/93e836ae281b37560a73a7e01d132ea12d53b5c1/index.js#L18

Looks like SWC has builtin TS support

https://github.com/swc-project/swc#parsers

**Comment by stefanpenner** [comment]
let me fix that

**Comment by stefanpenner** [comment]
should be fixed with released as v0.0.6 🎉

**Comment by stefanpenner** [comment]
Actually I didn't realize the parser needed to be explicitly selected, should be fixed now in v0.2.1 🎉via https://github.com/stefanpenner/broccoli-swc/commit/c1ae021a6ab4565b94325f10b562519accb2d4fe

**Comment by stefanpenner** [comment]
@lifeart  ^^
